//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================

// USER INCLUDES
#include <SI_EFM8UB1_Register_Enums.h>
#include "board.h"

//-----------------------------------------------------------------------------
// VBUS_ISR
//-----------------------------------------------------------------------------
//
// VBUS ISR Content goes here. Remember to clear flag bits:
// USB0CDSTA::DCDI (Data Contact Detect Complete)
// USB0CDSTA::ERR (USB Charger Detection Error)
// USB0CDSTA::PDI (Primary Detection Complete)
// USB0CDSTA::SDI (Secondary Detection Complete)
// USB0CF::VBUSI (VBUS Interrupt)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (VBUS_ISR, VBUS_IRQn)
{

}
